# site name
prefixName: Kaizyn's
siteName: Blog
# favicon and site master avatar
# ico
favicon: /images/favicon32.ico
# 头像
avatar: /img/custom/avatar.gif
# 站点url
url: https://kaizynx.github.io/
# 站点介绍(个人签名)
description: A Rubbish's Blog
# 站点cdn
cdn: https://cdn.jsdelivr.net/gh/KaizynX/cdn
pjax: 1
# 1开启
mathjax: 1

# 站点首页的公告信息
notice: 博客完善中..
# 懒加载的加载中图片
lazyloadImg: https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/post-loading.gif

# 图标来自：https://fontawesome.com/icons
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake}
  # 归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    # 技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o },
    # 转载: {path: /categories/转载/, fa: fa-book }
  # } }
  目录: { path: /categories, fa: fa-list-ul faa-vertical, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code } 
  } }
  标签: { path: /tags, fa: fa-tags }
  # 清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    # 书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    # 番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    # 歌单: {path: /music/, fa: fa-headphones },
    # 图集: {path: /tags/图集/, fa: fa-photo }
  # } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  大佬链: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我?: {path: /about/, fa: fa-meetup}, 
    主题: {path: https://github.com/honjun/hexo-theme-sakura, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number) 主页显示文章数
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/001.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/002.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/003.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/004.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/005.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/006.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/007.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/008.jpg
  - https://cdn.jsdelivr.net/gh/KaizynX/cdn/img/cover/009.jpg
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash 面板(置顶?) url, title, desc img
startdash: 
  - {url: https://github.com/honjun/hexo-theme-sakura, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://kaizynx.github.io/2018/11/04/template/, title: ACM模板, desc: 某菜鸡整理的板子, img: /img/startdash/acm.jpg}
  - {url: /, title: 空缺广告位, desc: qwq, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 9/24/2018

#社交按钮social  url, img PC端配置
social:
  github: {url: https://github.com/KaizynX, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  # wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  zhihu: {url: http://www.zhihu.com/people/kaizyn, img: /img/social/zhihu.png}
  email: {url: mailto:2291443901@qq.com, img: /img/social/email.svg}
  qq: {url: tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=2291443901, img: /img/social/qq.png}
  # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/KaizynX, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2291443901&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.gif
  # wechat: /img/custom/donate/WeChanQR.jpg
  # wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/KaizynX/cdn/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Lion.mp4

aplayer: 
  id: 2509579883
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: thHO16MtUqCFt5ytzki9wwNG-gzGzoHsz
v_appKey: RztxTMKSVDyuAaC0BVM1wPM1


# 文章加密
encrypt:
  enable: true
  default_abstract: 该文章被一股不可抗击的力量封印了
  default_message: 我们的接头暗号是?
